<?php

function my_acf_add_local_field_groups() {

	if( function_exists('acf_add_local_field_group') ):

		acf_add_local_field_group(array(
			'key' => 'group_5714ee0ed437a',
			'title' => 'Questions',
			'fields' => array(
				array(
					'key' => 'field_5714ee74effc3',
					'label' => 'Survey',
					'name' => 'survey',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5714ef45effc6',
					'min' => 1,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add Question',
					'sub_fields' => array(
						array(
							'key' => 'field_5714ef58effc7',
							'label' => 'Type',
							'name' => 'type',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '40',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'block' => 'Block Text',
								'emoji' => 'Emoji Response',
								'score' => 'Score Response',
								'text' => 'Text Response',
								'multiple' => 'Multiple/Single Choice',
								'group' => 'Multiple Questions',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5714f0d8effca',
							'label' => 'Allowed Number of Choices',
							'name' => 'allowed_choices',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5714ef58effc7',
										'operator' => '==',
										'value' => 'multiple',
									),
								),
							),
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 1,
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5a0aeff75df58',
							'label' => 'Add Image',
							'name' => 'add_image',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5a13fb33add31',
							'label' => 'Required',
							'name' => 'required',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5714ef58effc7',
										'operator' => '!=',
										'value' => 'block',
									),
								),
							),
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5714ef45effc6',
							'label' => 'Question',
							'name' => 'question',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '75',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 3,
							'new_lines' => 'wpautop',
						),
						array(
							'key' => 'field_5a0af0625df59',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5a0aeff75df58',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5714f021effc8',
							'label' => 'Options',
							'name' => 'options',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5714ef58effc7',
										'operator' => '==',
										'value' => 'multiple',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Option',
							'sub_fields' => array(
								array(
									'key' => 'field_5714f09ceffc9',
									'label' => 'Option',
									'name' => 'option',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
						array(
							'key' => 'field_57399f4166790',
							'label' => 'Answers',
							'name' => 'answers',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5714ef58effc7',
										'operator' => '==',
										'value' => 'group',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_57399f8766791',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Row',
							'sub_fields' => array(
								array(
									'key' => 'field_57399f8766791',
									'label' => 'Answer',
									'name' => 'answer',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
						array(
							'key' => 'field_57399fb566792',
							'label' => 'Questions',
							'name' => 'questions',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5714ef58effc7',
										'operator' => '==',
										'value' => 'group',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_57399fe066793',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Row',
							'sub_fields' => array(
								array(
									'key' => 'field_57399fe066793',
									'label' => 'M Question',
									'name' => 'm_question',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => 3,
									'new_lines' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'survey',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
		));

		acf_add_local_field_group(array(
			'key' => 'group_5a0af19bb1141',
			'title' => 'Settings',
			'fields' => array(
				array(
					'key' => 'field_5a0af1a186c0b',
					'label' => 'Start Date',
					'name' => 'start_date',
					'type' => 'date_time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'F j, Y g:i a',
					'return_format' => 'c',
					'first_day' => 1,
				),
				array(
					'key' => 'field_5a0af35a86c0d',
					'label' => 'End Date',
					'name' => 'end_date',
					'type' => 'date_time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'F j, Y g:i a',
					'return_format' => 'c',
					'first_day' => 1,
				),
				array(
					'key' => 'field_5a0af20786c0c',
					'label' => 'Submissions',
					'name' => 'submissions',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Once',
					'ui_off_text' => 'Multiple',
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'survey',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'side',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
		));

	endif;
}

add_action('acf/init', 'my_acf_add_local_field_groups');